"""create initial schema

Revision ID: 80f9930a0873
Revises: 
Create Date: 2026-09-23 15:50:52.968157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80f9930a0873'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dataset_name', sa.String(length=255), nullable=False),
    sa.Column('baseline_name', sa.String(length=255), nullable=True),
    sa.Column('has_baseline', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('column_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_percentage', sa.Float(), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('grade', sa.String(length=1), nullable=False),
    sa.Column('issue_count', sa.Integer(), nullable=False),
    sa.Column('anomaly_count', sa.Integer(), nullable=False),
    sa.Column('schema_issue_count', sa.Integer(), nullable=False),
    sa.Column('datatype_issue_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('column_metrics_json', sa.Text(), nullable=False),
    sa.Column('score_breakdown_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('findings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('issue_type', sa.String(length=50), nullable=False),
    sa.Column('column_name', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('prev_value', sa.Float(), nullable=True),
    sa.Column('curr_value', sa.Float(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('findings')
    op.drop_table('runs')
    # ### end Alembic commands ###
